### ISSUE TITLE
Can you add this function of the falling block??

### ISSUE THREAD

**Issue by NoteBlockMR** [Yancey2023/CommandFallingBlock#4]
https://github.com/Yancey2023/CommandFallingBlock/assets/170589000/75248b18-a359-4652-a0df-b6c4e6451dd7

I wish there was an option like this
I hope there is an option to add a command to the falling block

/execute at @e[type=minecraft:falling_block] run CMD

**Comment by Yancey2023** [comment]
you can use **/execute at @e[type=commandfallingblock:better_falling_block] run CMD**

**Comment by NoteBlockMR** [comment]
Good!!
