### ISSUE TITLE
I have an idea

### ISSUE THREAD

**Issue by NoteBlockMR** [Yancey2023/CommandFallingBlock#5]
Can you add a falling block as a snowball??

**Comment by Yancey2023** [comment]
Do you mean to throw blocks' item like the snowball?

**Comment by Yancey2023** [comment]
emmm, maybe you want falling blocks rendering the item?

**Comment by NoteBlockMR** [comment]
yes

**Comment by Yancey2023** [comment]
Looking for a mod that has a block just for showing items might be a better option.

**Comment by Yancey2023** [comment]
Looking for a mod that has a block just for showing items might be a better option.
